### ISSUE TITLE
Migrate CMS backend to Netlify CMS

### ISSUE THREAD

**Issue by EnMod** [EnMod/noelquiles.com#2]
Netlify CMS is a lot closer to what I was trying to use Contentful for anyway, and with no major config in my dev environment!  Plus it's FREE, and I'm liking what I'm seeing as I test, moreso than Contentful.  I dig.

This will include reverting my subdomain structure for js30 and my blog...will be using subdirectories instead.  This makes a lot more sense from a management perspective considering I would then be able to manage all my related pages from that one interface.  The biggest benefit is, single builds of my main site create rebuilds of the subdirectories, so that all works out.  One could argue that this is a downside, but considering it's all for my infrequently updated domain it isn't so bad.

- [ ] Get the dev environment set up in a new branch with [this guide](https://www.netlifycms.org/docs/add-to-your-site/)
- [ ] Create the Netlify CMS page structure in my views for main site, js30, and blog, eschewing all Contentful templating I worked so hard to implement 😭 😭 😭  
- [ ] Grab all the current data off of Contentful 💀 
- [ ] Put all that data into the new branch
- [ ] Test the pipeline extensively to fix any strange issues
- [ ] Push finalizing commit 
- [ ] Set up netlify redirects to redirect requests to the subdomains to point at the corresponding subdirectories
- [ ] Put up a [blog post](https://blog.noelquiles.com) about the process lol

**Comment by EnMod** [comment]
Lol change of plans, I misread the attribution.  I'll just make it more prominent using the wordmark as per latest guidelines

**Comment by EnMod** [comment]
Lol change of plans, I misread the attribution.  I'll just make it more prominent using the wordmark as per latest guidelines

**Comment by EnMod** [comment]
Lol change of plans, I misread the attribution.  I'll just make it more prominent using the wordmark as per latest guidelines

**Comment by EnMod** [comment]
Decided to migrate to DatoCMS after some choice words from @jescalan , definitely do not regret

**Comment by jescalan** [comment]
🎉🎉🎉
